// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceSense.Api.Data;

#nullable disable

namespace SpaceSense.Api.Migrations
{
    [DbContext(typeof(SatGuardDbContext))]
    partial class SatGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SpaceSense.Api.Models.Alerta", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("alerta_id");

                    b.Property<DateTime>("AlertaData")
                        .HasColumnType("TEXT")
                        .HasColumnName("alerta_data");

                    b.Property<string>("AlertaDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("alerta_descricao");

                    b.Property<string>("AlertaNivel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("alerta_nivel");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PLATAFORMA_plataforma_id");

                    b.Property<int>("SateliteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("satelite_id");

                    b.HasKey("AlertaId");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("SateliteId");

                    b.ToTable("ALERTAS");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("empresa_id");

                    b.Property<string>("EmpresaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa_nome");

                    b.Property<string>("EmpresaPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa_pais");

                    b.HasKey("EmpresaId");

                    b.ToTable("EMPRESAS");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.ObjetoEspacial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("objeto_id");

                    b.Property<int>("OrbitaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orbita_id");

                    b.Property<decimal>("Velocidade")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("velocidade");

                    b.HasKey("Id");

                    b.HasIndex("OrbitaId");

                    b.ToTable("ObjetosEspaciais");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Orbita", b =>
                {
                    b.Property<int>("OrbitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("orbita_id");

                    b.Property<decimal>("OrbitaAltitudeKm")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("orbita_altitude_km");

                    b.Property<string>("OrbitaCategoria")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("orbita_categoria");

                    b.Property<decimal>("OrbitaInclinacao")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("orbita_inclinacao");

                    b.HasKey("OrbitaId");

                    b.ToTable("ORBITAS");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Plataforma", b =>
                {
                    b.Property<int>("PlataformaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("plataforma_id");

                    b.Property<string>("PlataformaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("plataforma_nome");

                    b.Property<string>("PlataformaStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("plataforma_status");

                    b.HasKey("PlataformaId");

                    b.ToTable("PLATAFORMA");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plataforma_id");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_email");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_senha");

                    b.Property<string>("UsuarioTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_tipo");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.DetritoEspacial", b =>
                {
                    b.HasBaseType("SpaceSense.Api.Models.ObjetoEspacial");

                    b.Property<decimal>("DetritoRiscoColisao")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("detrito_risco_colisao");

                    b.Property<decimal>("DetritoTamanho")
                        .HasColumnType("decimal(4, 1)")
                        .HasColumnName("detrito_tamanho");

                    b.ToTable("DETRITO_ESPACIAL");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Satelite", b =>
                {
                    b.HasBaseType("SpaceSense.Api.Models.ObjetoEspacial");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("SateliteDataLancamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("satelite_data_lancamento");

                    b.Property<string>("SateliteFuncao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("satelite_funcao");

                    b.Property<string>("SateliteNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("satelite_nome");

                    b.Property<string>("SateliteStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT")
                        .HasColumnName("satelite_status");

                    b.HasIndex("EmpresaId");

                    b.ToTable("SATELITES");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Alerta", b =>
                {
                    b.HasOne("SpaceSense.Api.Models.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceSense.Api.Models.Satelite", "Satelite")
                        .WithMany()
                        .HasForeignKey("SateliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("Satelite");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Empresa", b =>
                {
                    b.OwnsOne("SpaceSense.Api.Models.Endereco", "EnderecoSede", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("endereco_estado");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("endereco_rua");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("EMPRESAS");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("EnderecoSede");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.ObjetoEspacial", b =>
                {
                    b.HasOne("SpaceSense.Api.Models.Orbita", "Orbita")
                        .WithMany()
                        .HasForeignKey("OrbitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orbita");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Usuario", b =>
                {
                    b.HasOne("SpaceSense.Api.Models.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("SpaceSense.Api.Models.DetritoEspacial", b =>
                {
                    b.HasOne("SpaceSense.Api.Models.ObjetoEspacial", null)
                        .WithOne()
                        .HasForeignKey("SpaceSense.Api.Models.DetritoEspacial", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceSense.Api.Models.Satelite", b =>
                {
                    b.HasOne("SpaceSense.Api.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceSense.Api.Models.ObjetoEspacial", null)
                        .WithOne()
                        .HasForeignKey("SpaceSense.Api.Models.Satelite", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
